//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("0.6.9")]
[assembly: AssemblyFileVersion("0.6.9")]
[assembly: AssemblyInformationalVersion("0.6.9")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2021 Phillip Sharpe")]

