//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake.AWS.S3")]
[assembly: AssemblyVersion("0.4.5")]
[assembly: AssemblyFileVersion("0.4.5")]
[assembly: AssemblyInformationalVersion("0.4.5")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2017 Phillip Sharpe")]

